// ── HVVC Events ──────────────────────────────────────────────
// Add new events here — both events.html and index.html pull from this file.

const HVVC_EVENTS = [
  {
    id: "spring-academy-1314-2026",
    title: "HVVC 13U–14U Developmental Spring Academy",
    tag: "Academy",
    dateISO: "2026-06-04",
    dateDisplay: "April 21 – June 4, 2026",
    dateRange: "April 21 – June 4 (Tuesdays & Thursdays)",
    time: "Wks 1–2: 4:30–5:30 PM  ·  Wks 3–7: 5:00–6:30 PM",
    location: "Beatrice Cannady Gym",
    description: "A developmental program that introduces young athletes to club-level volleyball, building foundational skills while emphasizing consistency, confidence, and game awareness. Combines structured skill work with competitive play to prepare participants for club season expectations.",
    expect: [
      "Foundational skill development",
      "Structured skill work & competitive play",
      "Club season preparation",
      "14 total sessions",
      "HVVC training shirt included",
    ],
    notes: "$230 · 14 sessions · All skill levels welcome",
    registerUrl: "https://hvvc.leagueapps.com/clubteams/4974095-13u-14u-spring-26",
    registerLabel: "Register Now →",
  },
  {
    id: "spring-academy-1012-2026",
    title: "HVVC 10U–11U Spring Academy",
    tag: "Academy",
    dateISO: "2026-05-27",
    dateDisplay: "April 6 – May 27, 2026",
    dateRange: "April 6 – May 27",
    location: "Happy Valley, OR",
    description: "A practice-focused developmental program introducing young athletes to club volleyball fundamentals. Emphasizes foundational skill development, team systems, positioning, and court awareness. Prepares athletes for the fall 2026–2027 club season.",
    expect: [
      "Foundational skill & systems training",
      "Team communication & responsibility",
      "Court awareness & positioning",
      "1–2 local scrimmages planned",
      "Club season preparation",
    ],
    notes: "No game participation — scrimmages only. ~10–14 athletes.",
    registerUrl: "https://hvvc.leagueapps.com/clubteams/4967122-10u-12u-spring-26",
    registerLabel: "Register Now →",
  },
  {
    id: "spring-academy-12u-2026",
    title: "HVVC 12U Spring Academy",
    tag: "Academy",
    dateISO: "2026-06-10",
    dateDisplay: "May 4 – June 10, 2026",
    dateRange: "May 4 – June 10 (Mon & Wed)",
    time: "5:30pm – 7:00pm",
    location: "Beatrice Cannady Elementary",
    description: "A practice-focused developmental team for young athletes who have demonstrated strong interest, potential, and readiness for the next step in their volleyball journey. Serves as an introduction to club volleyball and prepares athletes for the expectations, structure, and competitive environment of club play in the upcoming fall season.",
    expect: [
      "Strong foundational skill development",
      "Team systems, positioning & court awareness",
      "Confidence, communication & team responsibility",
      "11 training sessions",
      "Practice jersey included",
      "~12 athletes — high-quality reps & intentional coaching",
    ],
    notes: "$190 · Ages 11–12 · Questions: hvvc@hvvcvolleyballclub.com",
    registerUrl: "https://hvvc.leagueapps.com/clubteams/4989288-12u-spring-academy",
    registerLabel: "Register Now →",
  },
  {
    id: "banquet-2026",
    title: "HVVC End-of-Season Banquet",
    tag: "Team Event",
    dateISO: "2026-06-07",
    dateDisplay: "Sunday, June 7, 2026",
    time: "4:30 – 6:30 PM",
    location: "Adrienne Nelson High School — Commons",
    comingSoon: true,
  },
  {
    id: "summer-camp-2026",
    title: "HVVC Summer Camp 2026",
    tag: "Camp",
    dateISO: "2026-06-22",
    dateDisplay: "June 22–25, 2026",
    dateRange: "June 22–25 (Mon–Thu)",
    time: "11am–1pm (Grades 3–6)  ·  2pm–4pm (Grades 7–HS)",
    location: "Adrianne Nelson High School — Main Gym",
    description: "Join Happy Valley Volleyball Club for 4 days of high energy training, skill development, competition, and FUN led by HVVC Coaches! Whether you're newer to the game or looking to sharpen your skills before school and club season, this camp is designed to help athletes grow in a positive, competitive environment.",
    schedule: [
      "11am – 1pm — Grades 3–6",
      "2pm – 4pm — Grades 7–High School",
    ],
    expect: [
      "Skill training & drills",
      "Game play & competition",
      "Position-based instruction",
      "Serving, passing, setting, attacking & defense work",
      "High energy coaching from HVVC staff",
      "Fun, encouraging atmosphere focused on growth & confidence",
    ],
    notes: "All skill levels welcome!",
    bannerTitle: "Summer Camp 2026",
    pinBanner: true,
    registerUrl: "https://hvvc.leagueapps.com/clubteams/5011923-hvvc-summer-camp-2026",
    registerLabel: "Register Now →",
  },
  {
    id: "tryouts-14u-2026",
    title: "14s & Under Girls — 2026–2027 Tryouts",
    tag: "Tryouts",
    dateISO: "2026-11-08",
    dateDisplay: "Sunday, November 8, 2026",
    comingSoon: true,
  },
  {
    id: "tryouts-15u-2026",
    title: "15s & Older Girls — 2026–2027 Tryouts",
    tag: "Tryouts",
    dateISO: "2026-11-15",
    dateDisplay: "Sunday, November 15, 2026",
    comingSoon: true,
  },
];
